version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT = 3000
      - REDIS_URL=redis://redis:6379
      - DB_URL=mongodb://mongo:27017/faq
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongo:/data/db
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
volumes:
  mongo:
  redis:
